/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertHistoryRouteImport } from './routes/alert-history'
import { Route as AlertSettingsRouteImport } from './routes/alert-settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ImpactWallRouteImport } from './routes/impact-wall'
import { Route as IotSensorsRouteImport } from './routes/iot-sensors'
import { Route as MenuOptimizerRouteImport } from './routes/menu-optimizer'
import { Route as NgoRegistryRouteImport } from './routes/ngo-registry'
import { Route as PickupCalendarRouteImport } from './routes/pickup-calendar'
import { Route as QualityAlertsRouteImport } from './routes/quality-alerts'
import { Route as QualityScannerRouteImport } from './routes/quality-scanner'
import { Route as RedistributionRouteImport } from './routes/redistribution'
import { Route as ScanHistoryRouteImport } from './routes/scan-history'
import { Route as SurplusForecastRouteImport } from './routes/surplus-forecast'
import { Route as SustainabilityRouteImport } from './routes/sustainability'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertHistoryRoute = AlertHistoryRouteImport.update({
  id: '/alert-history',
  path: '/alert-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertSettingsRoute = AlertSettingsRouteImport.update({
  id: '/alert-settings',
  path: '/alert-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactWallRoute = ImpactWallRouteImport.update({
  id: '/impact-wall',
  path: '/impact-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const IotSensorsRoute = IotSensorsRouteImport.update({
  id: '/iot-sensors',
  path: '/iot-sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuOptimizerRoute = MenuOptimizerRouteImport.update({
  id: '/menu-optimizer',
  path: '/menu-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRegistryRoute = NgoRegistryRouteImport.update({
  id: '/ngo-registry',
  path: '/ngo-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupCalendarRoute = PickupCalendarRouteImport.update({
  id: '/pickup-calendar',
  path: '/pickup-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityAlertsRoute = QualityAlertsRouteImport.update({
  id: '/quality-alerts',
  path: '/quality-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityScannerRoute = QualityScannerRouteImport.update({
  id: '/quality-scanner',
  path: '/quality-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RedistributionRoute = RedistributionRouteImport.update({
  id: '/redistribution',
  path: '/redistribution',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanHistoryRoute = ScanHistoryRouteImport.update({
  id: '/scan-history',
  path: '/scan-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SurplusForecastRoute = SurplusForecastRouteImport.update({
  id: '/surplus-forecast',
  path: '/surplus-forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alert-history': typeof AlertHistoryRoute
  '/alert-settings': typeof AlertSettingsRoute
  '/dashboard': typeof DashboardRoute
  '/impact-wall': typeof ImpactWallRoute
  '/iot-sensors': typeof IotSensorsRoute
  '/menu-optimizer': typeof MenuOptimizerRoute
  '/ngo-registry': typeof NgoRegistryRoute
  '/pickup-calendar': typeof PickupCalendarRoute
  '/quality-alerts': typeof QualityAlertsRoute
  '/quality-scanner': typeof QualityScannerRoute
  '/redistribution': typeof RedistributionRoute
  '/scan-history': typeof ScanHistoryRoute
  '/surplus-forecast': typeof SurplusForecastRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alert-history': typeof AlertHistoryRoute
  '/alert-settings': typeof AlertSettingsRoute
  '/dashboard': typeof DashboardRoute
  '/impact-wall': typeof ImpactWallRoute
  '/iot-sensors': typeof IotSensorsRoute
  '/menu-optimizer': typeof MenuOptimizerRoute
  '/ngo-registry': typeof NgoRegistryRoute
  '/pickup-calendar': typeof PickupCalendarRoute
  '/quality-alerts': typeof QualityAlertsRoute
  '/quality-scanner': typeof QualityScannerRoute
  '/redistribution': typeof RedistributionRoute
  '/scan-history': typeof ScanHistoryRoute
  '/surplus-forecast': typeof SurplusForecastRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alert-history': typeof AlertHistoryRoute
  '/alert-settings': typeof AlertSettingsRoute
  '/dashboard': typeof DashboardRoute
  '/impact-wall': typeof ImpactWallRoute
  '/iot-sensors': typeof IotSensorsRoute
  '/menu-optimizer': typeof MenuOptimizerRoute
  '/ngo-registry': typeof NgoRegistryRoute
  '/pickup-calendar': typeof PickupCalendarRoute
  '/quality-alerts': typeof QualityAlertsRoute
  '/quality-scanner': typeof QualityScannerRoute
  '/redistribution': typeof RedistributionRoute
  '/scan-history': typeof ScanHistoryRoute
  '/surplus-forecast': typeof SurplusForecastRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alert-history'
    | '/alert-settings'
    | '/dashboard'
    | '/impact-wall'
    | '/iot-sensors'
    | '/menu-optimizer'
    | '/ngo-registry'
    | '/pickup-calendar'
    | '/quality-alerts'
    | '/quality-scanner'
    | '/redistribution'
    | '/scan-history'
    | '/surplus-forecast'
    | '/sustainability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alert-history'
    | '/alert-settings'
    | '/dashboard'
    | '/impact-wall'
    | '/iot-sensors'
    | '/menu-optimizer'
    | '/ngo-registry'
    | '/pickup-calendar'
    | '/quality-alerts'
    | '/quality-scanner'
    | '/redistribution'
    | '/scan-history'
    | '/surplus-forecast'
    | '/sustainability'
  id:
    | '__root__'
    | '/'
    | '/alert-history'
    | '/alert-settings'
    | '/dashboard'
    | '/impact-wall'
    | '/iot-sensors'
    | '/menu-optimizer'
    | '/ngo-registry'
    | '/pickup-calendar'
    | '/quality-alerts'
    | '/quality-scanner'
    | '/redistribution'
    | '/scan-history'
    | '/surplus-forecast'
    | '/sustainability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertHistoryRoute: typeof AlertHistoryRoute
  AlertSettingsRoute: typeof AlertSettingsRoute
  DashboardRoute: typeof DashboardRoute
  ImpactWallRoute: typeof ImpactWallRoute
  IotSensorsRoute: typeof IotSensorsRoute
  MenuOptimizerRoute: typeof MenuOptimizerRoute
  NgoRegistryRoute: typeof NgoRegistryRoute
  PickupCalendarRoute: typeof PickupCalendarRoute
  QualityAlertsRoute: typeof QualityAlertsRoute
  QualityScannerRoute: typeof QualityScannerRoute
  RedistributionRoute: typeof RedistributionRoute
  ScanHistoryRoute: typeof ScanHistoryRoute
  SurplusForecastRoute: typeof SurplusForecastRoute
  SustainabilityRoute: typeof SustainabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-history': {
      id: '/alert-history'
      path: '/alert-history'
      fullPath: '/alert-history'
      preLoaderRoute: typeof AlertHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-settings': {
      id: '/alert-settings'
      path: '/alert-settings'
      fullPath: '/alert-settings'
      preLoaderRoute: typeof AlertSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-wall': {
      id: '/impact-wall'
      path: '/impact-wall'
      fullPath: '/impact-wall'
      preLoaderRoute: typeof ImpactWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iot-sensors': {
      id: '/iot-sensors'
      path: '/iot-sensors'
      fullPath: '/iot-sensors'
      preLoaderRoute: typeof IotSensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-optimizer': {
      id: '/menu-optimizer'
      path: '/menu-optimizer'
      fullPath: '/menu-optimizer'
      preLoaderRoute: typeof MenuOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo-registry': {
      id: '/ngo-registry'
      path: '/ngo-registry'
      fullPath: '/ngo-registry'
      preLoaderRoute: typeof NgoRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup-calendar': {
      id: '/pickup-calendar'
      path: '/pickup-calendar'
      fullPath: '/pickup-calendar'
      preLoaderRoute: typeof PickupCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-alerts': {
      id: '/quality-alerts'
      path: '/quality-alerts'
      fullPath: '/quality-alerts'
      preLoaderRoute: typeof QualityAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-scanner': {
      id: '/quality-scanner'
      path: '/quality-scanner'
      fullPath: '/quality-scanner'
      preLoaderRoute: typeof QualityScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redistribution': {
      id: '/redistribution'
      path: '/redistribution'
      fullPath: '/redistribution'
      preLoaderRoute: typeof RedistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-history': {
      id: '/scan-history'
      path: '/scan-history'
      fullPath: '/scan-history'
      preLoaderRoute: typeof ScanHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surplus-forecast': {
      id: '/surplus-forecast'
      path: '/surplus-forecast'
      fullPath: '/surplus-forecast'
      preLoaderRoute: typeof SurplusForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertHistoryRoute: AlertHistoryRoute,
  AlertSettingsRoute: AlertSettingsRoute,
  DashboardRoute: DashboardRoute,
  ImpactWallRoute: ImpactWallRoute,
  IotSensorsRoute: IotSensorsRoute,
  MenuOptimizerRoute: MenuOptimizerRoute,
  NgoRegistryRoute: NgoRegistryRoute,
  PickupCalendarRoute: PickupCalendarRoute,
  QualityAlertsRoute: QualityAlertsRoute,
  QualityScannerRoute: QualityScannerRoute,
  RedistributionRoute: RedistributionRoute,
  ScanHistoryRoute: ScanHistoryRoute,
  SurplusForecastRoute: SurplusForecastRoute,
  SustainabilityRoute: SustainabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
